# Generated by Django 3.1.1 on 2020-09-30 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cargomanager', '0002_order_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='addtime',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='saler',
            field=models.ForeignKey(default=1.2, on_delete=django.db.models.deletion.CASCADE, to='cargomanager.staff'),
            preserve_default=False,
        ),
    ]
