# Generated by Django 3.1.1 on 2020-09-30 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargomanager', '0003_auto_20200930_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.CharField(default='', max_length=100),
        ),
    ]
